const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const autoprefixer = require('autoprefixer');

const env = process.env.NODE_ENV || 'development';
// set to 'production' or 'development' in your env

const finalCSSLoader = (env === 'production') ? MiniCssExtractPlugin.loader : { loader: 'style-loader' };


module.exports = {
    mode: env,
    entry: ['./src'], // this is where our app lives
    devtool: 'source-map', // this enables debugging with source in chrome devtools
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: [ // here's the part you want
                    { loader: 'babel-loader' },
                    { loader: 'eslint-loader' },
                ],
            },
            {
                test: /\.s?css/,
                use: [
                    finalCSSLoader,
                    {
                        loader: 'css-loader',
                        options: {
                            sourceMap: true,
                        },
                    },
                    {
                        loader: 'postcss-loader',
                        options: {
                            plugins: () => [autoprefixer()],
                            sourceMap: true,
                        },
                    },
                    {
                        loader: 'sass-loader',
                        options: {
                            sourceMap: true,
                        },
                    },
                ],
            },
            {
                test: /\.(jpe?g|png|gif|svg)$/,
                use: [
                    {
                        loader: 'file-loader',
                        options: {
                            useRelativePath: true,
                            name: '[name].[ext]',
                        },
                    },
                    {
                        loader: 'image-webpack-loader',
                        options: {
                            mozjpeg: {
                                progressive: true,
                                quality: 65,
                            },
                            // optipng.enabled: false will disable optipng
                            optipng: {
                                enabled: false,
                            },
                            pngquant: {
                                quality: [0.65, 0.90],
                                speed: 4,
                            },
                            gifsicle: {
                                interlaced: false,
                            },
                            // the webp option will enable WEBP
                            webp: {
                                quality: 75,
                            },
                        },
                    },
                    {
                        loader: 'url-loader',
                        options: {
                            limit: 8192,
                        },
                    },
                ],
            },
        ],
    },
    plugins: [
        new MiniCssExtractPlugin(),
        new HtmlWebpackPlugin({ // tells webpack that we want it to know that we have a src/index.html file and we want it to be available as just index.html in our final product.
            template: './src/index.html',
            filename: './index.html',
        }),
    ],
    devServer: {
        hot: true,
    },
};

/*
-->
    src/ #all the source html,js,css,scss files for your app
    dist/  #autogenerated directory where webpack will put your bundle files
*/
